# Numpy

***
- Numerical Python


- 파이썬의 고성능 과학 계산용 패키지


- Matrix와 Vector와 같은 Array 연산의 사실상의 표준
***

## Numpy 특징


***
- 일반 List에 비해 빠르고, 메모리 효율적


- 반복문 없이 데이터 배열에 대한 처리를 지원함.


- 선형대수와 관련된 다양한 기능을 제공함


- C ,C++ , 포트란 등의 언어와 통합 가능
***

## Numpy 모듈 호출

In [2]:
import numpy as np

## Array 생성

In [114]:
test_array = np.array(["1","2",3,4],float) # list와 달리 string, integer 타입이어도 float로 지정할 시 float 선언 

print(test_array)

[1. 2. 3. 4.]


***

- numpy는 np.array 함수를 활용하여 배열을 생성함 - **ndarray(다차원 행렬구조)**


- numpy는 하나의 데이터 type만 배열에 넣을 수 있다.


- LIst와 가장 큰 차이점, Dynamic typing not supported


- C의 Array를 사용하여 배열을 생성함
***

In [8]:
type(test_array[3])

numpy.float64

In [102]:
a = [1,2,3,4,5]

In [103]:
b = a

In [104]:
b[2] = 5

In [105]:
a  # a 와 b가 가르키는 공간이 같기 때문에 변함.

[1, 2, 5, 4, 5]

Python list는 값 대신 메모리 주소가 들어감.

copy를 하더라도 메모리 주소가 들어가므로 한 단계 바뀐다 하더라도 그 주소가 들어가게됨.

In [116]:
test_array

array([1., 2., 3., 4.])

**shape** : Array(vector, matrix, tensor)의 크기, 형태 등에 대한 정보

In [117]:
test_array.shape

(4,)

In [129]:
test_matrix = [[1,2,3,4],[3,4,5,6]]
np.array(test_matrix,int)

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [132]:
np.array(test_matrix,int).shape

(2, 4)