### 1. numpy 호출

In [1]:
import numpy as np

### 2. array 생성

In [14]:
# 기존의 파이썬은 다양한 타입이 리스트에 들어감
# 그러나 넘파이의 array에서는 허락하지않음
test_array = np.array(["1","4",5,8], float)
test_array

array([1., 4., 5., 8.])

In [15]:
type(test_array[3])

numpy.float64

In [17]:
# array 데이터의 type 출력
test_array.dtype

dtype('float64')

In [18]:
# array의 shape 반환
test_array.shape

(4,)

In [19]:
# matrix형태의 shape 반환
# 차원이 늘어날때마다 raw가 밀림
np.array([["1","4",5,8]], float).shape

(1, 4)

In [20]:
# 차원의 개수 확인
np.array(test_array).ndim

1

In [23]:
# 데이터의 개수
np.array(test_array).size

4

In [27]:
# reshape - array의 shape의 크기를 변경함
test_matrix = [[1,2,3,4],[1,2,3,5]]
np.array(test_matrix).shape

(2, 4)

In [29]:
# 차원 수 1 증가
np.array(test_matrix).reshape(2,2,2) 

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 5]]])

In [31]:
# sklearn을 사용할 떄 많이 사용
# -1 사용시 size를 기반으로 row개수 선정
# row의 개수는 모르지만 column의 개수는 2개로 고정된 채 생성
np.array(test_matrix).reshape(-1,2).shape

(4, 2)

In [35]:
print(test_matrix)
t_m = np.array(test_matrix).reshape(-1,2)
print(t_m)

[[1, 2, 3, 4], [1, 2, 3, 5]]
[[1 2]
 [3 4]
 [1 2]
 [3 5]]


#### flatten

- 다차원 array를 1차원 array로 변환

In [49]:
test_matrix = [[[1,2,3,4],[1,2,5,6]],[[1,2,3,4],[1,2,3,4]]]
print(test_matrix)
# 차원 수 확인
print(np.array(test_matrix).ndim)
# 모양 확인
print(np.array(test_matrix).shape)

[[[1, 2, 3, 4], [1, 2, 5, 6]], [[1, 2, 3, 4], [1, 2, 3, 4]]]
3
(2, 2, 4)


In [51]:
# 3차원 데이터를 1차원으로
print(np.array(test_matrix).flatten())
# 1차원 벡터로 변환됨을 확인
print(np.array(test_matrix).flatten().shape)

[1 2 3 4 1 2 5 6 1 2 3 4 1 2 3 4]
(16,)


In [53]:
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
y = np.dot(X, np.array([1, 2]))