In [1]:
import numpy as np

In [3]:
# 1차원 벡터
c = np.array([1,2,3])
print(c.shape)

# 첫번째 요소
print(c[0])

(3,)
1


In [9]:
# row가 존재하는 벡터
r = np.array([[1,2,3]])
print(r)
print(r.shape)
print(r[0,1])

[[1 2 3]]
(1, 3)
2


In [11]:
# 0으로 채워진 2*2 행렬
a = np.zeros((2,2))
print(a)
# 1로 채워진 2*2 행렬
b = np.ones((2,2))
print(b)

# 같은 수로만 채워진 행렬
c = np.full((2,2),7)
print(c)

# 랜덤 values로 채워진 행렬
d = np.random.random((2,2))
print(d)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[0.88532142 0.96061066]
 [0.57641979 0.98922616]]


In [12]:
# 행렬 생성
a = np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
# 행렬 생성 2
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
# a 전치 행렬
a.T

array([[1, 3, 5],
       [2, 4, 6]])

In [15]:
# 행렬 곱 계산
np.dot(a,b)

array([[11, 14, 17, 20],
       [23, 30, 37, 44],
       [35, 46, 57, 68]])

In [16]:
# b와 a의 사이즈가 맞지 않아 에러 발생
np.dot(b,a)

ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

In [18]:
# coefficient matrix
a = np.array([[60,5.5,1],[65,5,0],[55,6,1]])
b = np.array([60,70,78])

print(a)
print(b)

[[60.   5.5  1. ]
 [65.   5.   0. ]
 [55.   6.   1. ]]
[60 70 78]


In [19]:
# 단위행렬
eye3 = np.eye(3)
eye3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# a 역행렬
from numpy.linalg import inv
a_inv = inv(a)
a_inv

array([[ 0.08695652,  0.00869565, -0.08695652],
       [-1.13043478,  0.08695652,  1.13043478],
       [ 2.        , -1.        , -1.        ]])

In [21]:
# 단순곱이라 단위행렬이 안됨
a * a_inv

array([[ 5.21739130e+00,  4.78260870e-02, -8.69565217e-02],
       [-7.34782609e+01,  4.34782609e-01,  0.00000000e+00],
       [ 1.10000000e+02, -6.00000000e+00, -1.00000000e+00]])

In [22]:
# aa-1 = E가 성립
a.dot(a_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])