In [1]:
import numpy as np

In [2]:
n = 3
np.arange(n**2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
def n_size_ndarray_creation(n, dtype = np.int) :
    return np.array(range(n**2),dtype = dtype).reshape(n,n)

In [4]:
n_size_ndarray_creation(3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
def change_shape_of_ndarray(X,n_row) :
    return X.flatten() if n_row == 1 else X.reshape(n_row,-1)

In [10]:
X = np.ones((32,32),dtype = np.int)

In [12]:
change_shape_of_ndarray(X,2)

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])