# Numpy

**Numerical Python**의 줄임말로, 파이썬에서 산술 계산을 위한 가장 중요한 필수 패키지 중 하나이다.

In [1]:
# numpy 호출

import numpy as np

In [2]:
# 임의의 값 생성

data = np.random.randn(2,3)

In [3]:
data

array([[ 1.18657734,  0.83511167, -0.57132033],
       [-0.04868311,  0.51100257,  2.37027773]])

In [4]:
data*10

array([[11.86577339,  8.35111672, -5.71320332],
       [-0.48683106,  5.11002574, 23.70277725]])

In [5]:
data + data

array([[ 2.37315468,  1.67022334, -1.14264066],
       [-0.09736621,  1.02200515,  4.74055545]])

**ndarray**는 같은 종류의 데이터를 담을 수 있는 포괄적인 다차원 배열이다.

ndarray의 모든 원소는 같은 자료형이어야 한다.

**shape** : 모든 배열의 각 차원의 크기를 알려준다.


**dtype** : 튜플과 배열에 저장된 자료형을 알려주는 객체

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

배열을 생성하는 가장 쉬운 방법은 array 함수를 이용하는 것이다

In [8]:
data1 = [6,7,8,0,1]

arr1 = np.array(data1)

arr1

array([6, 7, 8, 0, 1])

같은 길이의 리스트를 가진 데이터는 다차원 배열로 변환 가능하다.

In [9]:
data2 = [[1,3,4,5,6],[4,2,8,7,9.1]]

arr2 = np.array(data2)

arr2

array([[1. , 3. , 4. , 5. , 6. ],
       [4. , 2. , 8. , 7. , 9.1]])

In [10]:
arr2.shape

(2, 5)

명시적으로 지정하지 않는 한 np.array는 생성될 때 적절한 자료형을 추론한다. 추론된 자료형은 dtype 객체에 저장된다.

In [11]:
arr1.dtype

dtype('int32')

In [12]:
arr2.dtype

dtype('float64')

**np.zeros** , **np.ones** 함수는 주어진 길이나 모양에 각각 0과 1이 들어 있는 배열을 생성한다.

이런 메소드를 사용해 다차원 배열을 생성하려면 원하는 형태의 튜플을 넘기면 된다.

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

**arange**는 파이썬의 range 함수의 배열 버전이다.

In [16]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### ndarray의 dtype

**dtype**은 ndarray가 메모리에 있는 특정 데이터를 해석하기 위해 필요한 정보를 담고 있는 특수한 객체이다

In [17]:
arr1 = np.array([1,2,3],dtype = np.float64)

In [18]:
arr2 = np.array([1,2,3],dtype = np.int32)

In [19]:
arr1.dtype

dtype('float64')

In [20]:
arr2.dtype

dtype('int32')

ndarray의 astype 메소드를 사용해서 배열의 dtype을 다른 형으로 명시적으로 변한이 가능하다.

In [21]:
arr = np.array([1,2,3,4,5])

arr.dtype

dtype('int32')

In [22]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

소수가 있는 실수형을 정수형으로 변환시 소수점 아래 자리는 버려진다.

In [23]:
arr1 = np.array([1.2,3.1,-1.5,2])

arr1.dtype

dtype('float64')

In [24]:
int_arr1 = arr1.astype(np.int32)
int_arr1

array([ 1,  3, -1,  2])

숫자 형식의 문자열을 담고 있는 배열이 있다면 astype을 사용하여 숫자로 변환 할 수 있다.

In [25]:
arr2 = np.array(['1','15','2.5'],dtype = np.string_)
arr2

array([b'1', b'15', b'2.5'], dtype='|S3')

In [26]:
arr2.astype(float)

array([ 1. , 15. ,  2.5])

### Numpy 배열의 산술 연산

배열의 중요한 특징은 for문을 작성하지 않고 데이터를 일괄 처리할 수 있다는 것이다.
이를 **벡터화**라고 하는데, 같은 크기의 배열 간의 산술 연산은 배열의 각 원소 단위로 적용된다.

In [27]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [28]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [29]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

스칼라 인자가 포함된 산술 연산의 경우 배열 내의 모든 원소에 스칼라 인자가 적용된다.

In [30]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [31]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

같은 크기를 가지는 배열 간의 비교 연산은 불리언 배열을 반환한다.

In [32]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [33]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### 색인과 슬라이싱

In [34]:
arr = np.arange(9)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
arr[5]

5

In [36]:
arr[5:8]

array([5, 6, 7])

In [37]:
arr[5:8] = 12

arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8])

arr[5:8] = 12 처럼 배열 조각에 스칼라 값을 대입하면 12가 선택 영역 전체로 전파된다. 즉 데이터는 복사되지 않고 그대로 원본 배열에 변경을 반영한다.

In [38]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

arr_slice의 값을 변경하면 원래 배열인 arr의 값도 바꾸어 있음을 알 수 있다.

In [39]:
arr_slice[1] = 12345

arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8])

단순히 [:]로 슬라이스를 하면 배열의 모든 값을 배열한다.

In [40]:
arr_slice[:] = 64

arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8])

다차원 배열에서는 각 색인에 해당하는 요소는 스칼라 값이 아니라 1차원 배열이다.

In [41]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr2d[2]

array([7, 8, 9])

개별 요소는 다음 두 표현을 사용하여 접근한다. 

In [42]:
arr2d[0][2]

3

In [43]:
arr2d[0,2]

3

In [44]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [45]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
arr_values = arr3d[0].copy()

ndarray 슬라이스의 복사본을 얻고자 할 때는 arr3d[0].copy()를 사용해서 배열을 복사해야 한다.

In [47]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
arr3d[0] = arr_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [49]:
arr3d[1,0]

array([7, 8, 9])

In [50]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [51]:
x[0] # 2번에 걸친 인덱싱으로 arr3d[1,0]과 동일한 값이 나온다

array([7, 8, 9])

### 슬라이스로 선택하기

파이썬의 리스트 같은 1차원 객체처럼 ndarray는 익숙한 문법으로 슬라이싱 할 수 있다.

In [52]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8])

In [53]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [54]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr2d[:2]

# arr2d의 첫번째 행부터 2번째 행까지

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
arr2d[:2,1:]

# arr2d의 시작부터 2번째 행까지, 2번째 열부터 끝까지

array([[2, 3],
       [5, 6]])

In [57]:
arr2d[1,:2]

# 2번째 행을 출력하되 2번째 열 까지만 출력

array([4, 5])

In [58]:
arr2d[2,1:3]

# 3번째 행을 출력하되 처음 제외 나머지 열만 출력

array([8, 9])

In [59]:
arr2d[:,:1]

# 그냥 콜론만 사용시 전체 축을 선택한다는 의미

array([[1],
       [4],
       [7]])

슬라이싱 구문에 값을 대입하면 선택 영역 전체에 값이 대입된다.

In [60]:
arr2d[:2,1:] = 0

arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### 팬시 색인(Fancy indexing)

정수 리스트(혹은 배열)를 이용하여 여러 개를 동시에 선택하는 방식이다.

In [61]:
arr = np.empty((8,4))

for i in range(8) :
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [62]:
arr[[4,1,6,7]]

# 특정한 순서로 행을 선택할 시 그냥 원하는 순서대로 ndarray나 리스트에 입력하면 된다.

array([[4., 4., 4., 4.],
       [1., 1., 1., 1.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [63]:
arr[[-1,-2,-3]]

# 색인으로 음수를 사용하면 끝에서부터 선택된다.

array([[7., 7., 7., 7.],
       [6., 6., 6., 6.],
       [5., 5., 5., 5.]])

In [64]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [65]:
arr[[0,1,2,3],[0,1,2,3]]

# 첫번째 행부터 4번째 행까지, 각 1,2,3,4번째 원소 값

array([ 0,  5, 10, 15])

### 배열 전치와 축 바꾸기

배열 전치는 데이터를 복사하지 않고 데이터의 모양이 바뀐 뷰를 반환하는 특별한 기능이다.

ndarray는 transpose 메소드와 t라는 이름의 특수한 속성을 가지고 있다.

In [66]:
arr = np.arange(15).reshape((3,5))

arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [67]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

행렬 계산을 할 때 행렬의 내적은 **np.dot**을 이용해서 구할 수 있다.

In [68]:
arr = np.random.randn(6,3)
arr

array([[ 1.27333832,  0.2196318 ,  0.09756631],
       [ 0.62523052, -1.67589363,  0.33210862],
       [ 1.07933981,  0.24676698,  0.76809551],
       [ 1.81555469,  1.56062639, -1.00240553],
       [-1.29030345, -0.00413535,  1.34645691],
       [-1.25526637, -0.11307113,  0.83026395]])

In [69]:
np.dot(arr,arr.T)

array([[ 1.67914779,  0.46045305,  1.50350286,  2.55677753, -1.51253225,
        -1.542207  ],
       [ 0.46045305,  3.3098288 ,  0.51637211, -1.81321115, -0.35263673,
        -0.31959783],
       [ 1.50350286,  0.51637211,  1.81583908,  1.57476834, -0.35948884,
        -0.74503918],
       [ 2.55677753, -1.81321115,  1.57476834,  6.7366104 , -3.69876607,
        -3.28772771],
       [-1.51253225, -0.35263673, -0.35948884, -3.69876607,  3.4778463 ,
         2.73805674],
       [-1.542207  , -0.31959783, -0.74503918, -3.28772771,  2.73805674,
         2.27781696]])

다차원 배열의 경우 transpose 메소드는 튜플로 축 번호를 받아서 치환한다

In [70]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [71]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [72]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

### 유니버설 함수 : 배열의 각 원소를 빠르게 처리하는 함수

ndarray 안에 있는 데이터 원소별로 연산을 수행 하는 함수다.

하나 이상의 스칼라 결과값을 반환하는 간단한 함수를 고속으로 수행할 수 있는 벡터화된 함수.

In [74]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [76]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

위 함수들은 **단항 유니버설 함수**라고 함.

add나 maximum처럼 2개의 인자를 취해서 단일 배열을 반환하는 함수는 **이항** 유니버설 함수라고 한다

In [78]:
x = np.random.randn(8)

x

array([-0.64127322, -0.68065631,  0.52564763,  1.45330453, -0.48529864,
       -1.02696758,  0.64846667,  0.96091696])

In [77]:
y= np.random.randn(8)

y

array([ 1.51690216, -1.46922802,  0.2933398 , -0.52517076,  2.13903689,
        1.2749621 , -1.08361667, -2.03868137])

In [79]:
np.maximum(x,y)

array([ 1.51690216, -0.68065631,  0.52564763,  1.45330453,  2.13903689,
        1.2749621 ,  0.64846667,  0.96091696])

여기서 numpy.maximum은 x와 y의 원소별로 가장 큰 값을 계산한다.

### 배열을 이용한 배열지향 프로그래밍

numpy 배열을 사용하면 반복문을 작성하지않고 간결한 배열 연산을 사용해 많은 종류의 데이터 처리 작업을 할 수 있다.

배열 연산을 사용해서 반복문을 명시적으로 제거하는 기법을 흔히 벡터화라고 부르는데, 일반적으로 벡터화된 배열에 대한 산술 연산은 순수 파이썬 연산에 비해 빠르다.

#### 배열 연산으로 조건절 표현하기

**numpy.where** 함수는 x if 조건 else y 같은 삼항식의 벡터화된 버전이다.

In [80]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])

yarr = np.array([2.1,2.2,2.3,2.4,2.5])

cond = np.array([True,False,True,True,False])

cond의 값이 True일 때는 xarr의 값을 취하고 아니면 yarr의 값을 취하고 싶다면 리스트표기법을 이용해서 작성할 수 있다.

In [83]:
result = [(x if c else y)
         for x,y,c in zip(xarr,yarr,cond)]

result

[1.1, 2.2, 1.3, 1.4, 2.5]

위와 같은 방법은 순수 파이썬으로 수행되므로 큰 배열은 빠르게 처리 하지 못한다.

또한 다차원 배열에서는 사용할 수 없다.

In [85]:
result = np.where(cond,xarr,yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

데이터 분석에서 일반적인 where의 사용은 다른 배열에 기반한 새로운 배열을 생성한다.

In [87]:
arr = np.random.randn(4,4)
arr

array([[-1.83496148,  0.11624276,  1.41909501,  0.79637514],
       [-0.22099607,  1.18136451, -0.61929889,  1.45837031],
       [-0.10151902,  1.76262218, -1.01014005,  1.74556583],
       [ 1.2176986 ,  0.75849163, -0.62435978, -0.80169175]])

In [88]:
arr > 0

array([[False,  True,  True,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [ True,  True, False, False]])

In [90]:
np.where(arr > 0,2,-2)

# 양수는 모두 2로 음수는 모두 -2로

array([[-2,  2,  2,  2],
       [-2,  2, -2,  2],
       [-2,  2, -2,  2],
       [ 2,  2, -2, -2]])

np.where를 사용할 때 스칼라 값과 배열을 조합할 수 있다.

In [91]:
np.where(arr > 0,2,arr) # 양수인 경우에만 2를 대입한다.

array([[-1.83496148,  2.        ,  2.        ,  2.        ],
       [-0.22099607,  2.        , -0.61929889,  2.        ],
       [-0.10151902,  2.        , -1.01014005,  2.        ],
       [ 2.        ,  2.        , -0.62435978, -0.80169175]])