In [1]:
import numpy as np

In [5]:
data = np.random.randn(2,3)

In [6]:
data

array([[ 1.25722785, -1.49002899,  0.30876451],
       [-0.82846284, -0.51448753, -1.02307674]])

In [7]:
data*10

array([[ 12.57227845, -14.90028987,   3.08764509],
       [ -8.28462844,  -5.14487527, -10.23076738]])

In [8]:
data + data

array([[ 2.51445569, -2.98005797,  0.61752902],
       [-1.65692569, -1.02897505, -2.04615348]])